### ISSUE TITLE
invalid error when trying to load TIBOYCE on calculator

### ISSUE THREAD

**Issue by Andrewb9** [calc84maniac/tiboyce#113]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.6.0
**TI-Boy CE version:** ALPHA v0.1.3
**Describe your issue:**  
 I have followed the instructions on the video as well as I could(I am using a mac). But whenever I try to run the TIBOYCE program an INVALID error posts. I have update the TI OS, I've tried deleting and reinstalling TIBOYCE. I have tried to look in the comments for a solutions but cannot seem to find any. If anyone is still active on here any help would be greatly appreciated

What are the steps to reproduce this issue?
-------------------------------------------
1. pgrm
2. 1
3.enter

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
ERROR: INVALID

**Comment by jacobly0** [comment]
As you can see [here](https://github.com/calc84maniac/tiboyce#running-the-emulator) you are probably missing the `Asm(` token.

**Comment by jacobly0** [comment]
Sorry but TI has controversially removed assembly support in OS 5.6.0 so you are out of luck for now.

**Comment by Andrewb9** [comment]
is there any way i could revert to OS 5.4?

**Comment by critor** [comment]
No, it's too late now.

How did you learn about the 5.6 update ?

**Comment by adriweb** [comment]
Looks like it didn't work initially for some reason (OS < 5.3.0 if he didn't use the `Asm(` token?) so he tried to update to the latest version by going to TI's website :(

**Comment by debrouxl** [comment]
Indeed, at the time of this writing, it's too late for your calculator to be able to use TI-Boy CE, or any other native code program. You're one of the first of many victims of TI's extremely anti-user move...

What you can do is:
* complain to TI-Cares about TI's move, which does not only prevent you from playing games, there are also useful non-game native code programs;
* strongly warn people around you against ever upgrading the OS of their TI-84+CE / TI-84+CE-T / TI-83 Premium CE calculators (and Python Edition variants thereof), at least if the current OS fulfills the functionality they desire from it, and the standardized tests they take don't mandate the usage of the very latest current version;
* advise people around you to buy non-TI calculator models, especially if your curriculum does not mandate a TI calculator. Other manufacturers remain more open-minded than TI, whose Nspire series has always been officialy closed to native code programming, negating an item which historically gave TI calculators significant success in the marketplace.

For instance, in the same (or better !) price tag range, NumWorks' hardware and software aren't perfect, but the initial hardware, which was already much more powerful than the 84+CE(-T)PE / 83PCEEP, was succeeded by significantly upgraded hardware last year, and the software keeps improving quickly. NumWorks' official open-source "Epsilon" OS has reached largely the same functionality level as the 84+CE(-T) PE / 83PCE EP by now, and there are third-party forks, mainly "Omega", which add great new capabilities, especially a port of the powerful giac engine (used in xcas), which will never be available on your 84+CE and models of the same family because the hardware is way too weak.

The Casio fx-CG50 (Graph 90+E in France) and the HP Prime G2 are two other interesting choices, if more expensive.

**Comment by Kan18** [comment]
If you are still on 5.6.0 and still have a TI calculator, you might want to try using arTifiCE ( https://yvantt.github.io/arTIfiCE/ ) to regain the ability to run assembly code on your calculator.

**Comment by spiderkiley4** [comment]
This was a while ago so I don't know if you still need this but you can install this https://yvantt.github.io/arTIfiCE/
