### ISSUE TITLE
What appvars are needed for playing pokemon on TiBoy

### ISSUE THREAD

**Issue by NiknutNerd** [calc84maniac/tiboyce#122]
I have been playing pokemon on my calculator and it ran out of ram. I was wondering if I could delete some of the app vars that had to do with it. I might have accidentally downloaded all of the stuff multiple times.

**Comment by Eeems** [comment]
You'll need all the appvars generated by converting the rom. Have you made sure they are all in the archive? Resending them to your calculator shouldn't be an issue since they would just overwrite the one you already sent.

**Comment by NiknutMusic** [comment]
Thank you! I really didn't expect a response. There are many with similar names that I was wondering if they were copies. There is PokeR01 PokeR02 PokeR03 etc. and others in a similar vein0

**Comment by Eeems** [comment]
Yeah, those are all the different parts of the rom. Due to size limitations it has to be broken up into various different files.

Since you are running out of ram, I would highly recommend going through all the programs and appvars and archiving them. If that doesn't help, maybe delete some unrelated ones.

**Comment by NiknutMusic** [comment]
I believe I have gotten everything and now I can play! Thank you
