### ISSUE TITLE
Pokemon games have a diagonal line of screen tearing

### ISSUE THREAD

**Issue by BeanieBen9990** [calc84maniac/tiboyce#128]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** … (see in `2nd`+`mem` ->`About`)
TI-OS 5.6.1.0012 (but also happened on 5.4.0)
**TI-Boy CE version:** … (shown on the TI-Boy menu, or if you built it yourself please specify which commit)
TI-Boy CE Alpha v0.1.3
**Describe your issue:**  
… (including, if applicable what you expect vs. what happens)  
When playing any Pokemon gameboy game I've tried, (Red, Blue, Green, + Yellow) there is a diagonal screen tear from the top left to the bottom right. Having the screen flicker, like walking in and out of a building, or walking up and down, especially in rooms where there are lines on the floor, like Prof. Oak's Lab, are the best way to see this issue.
What are the steps to reproduce this issue?
-------------------------------------------
1. Load any Pokemon gameboy rom
2. Play the game
3. Notice screen tear?

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by calc84maniac** [comment]
Unfortunately this is a side effect of TI using a sideways portrait screen while using a landscape frame buffer (you can actually see this throughout the OS and in most games). It's possible to change the buffer orientation, but since the Game Boy renders in landscape it would be a significant performance hit in this case.

TI-Boy does manage to avoid this display glitch in the "no scaling" mode though, because it can copy the whole buffer to the LCD memory before it displays that area. Use that mode if you want the most "authentic" appearance (even if it's a bit small).

**Comment by BeanieBen9990** [comment]
Cool! Well thanks anyway!
