### ISSUE TITLE
Pokémon gold slowdown

### ISSUE THREAD

**Issue by Tchoupislayer** [calc84maniac/tiboyce#139]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.6.1.0012
**TI-Boy CE version:** v0.1.3
**Describe your issue:**  I own a ti 83 premium ce Python edition. I can launch pokémon gold and play it but it slowdown (speed is about 50%). I hadn't this issue with pokemon red or pokemon blue. Is it because this is a gbc game played on a gb and is there something I can do to resolve this issue ?  

What are the steps to reproduce this issue?
-------------------------------------------
1. Get the rom 
2. Convert it 
3. Play it

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by calc84maniac** [comment]
This is a performance issue that has been mostly resolved now in the development branch, so it should be fixed in the next release. It's only barely at full speed though, so it still won't benefit from turbo mode as much as Red/Blue.

I'm hoping to get to a new release point fairly soon, but it's also possible to build the dev version now if you accept some extra risk of crashes (I'm not currently aware of actual instability issues, but you never know). Instructions on how to do so are in my response to #131.

**Comment by Tchoupislayer** [comment]
Thank you for your answer. I love taking risks so i'll install the dev version. Once again thank you very much

**Comment by Tchoupislayer** [comment]
Oh I guess i'll just wait for a release since I can't resolve the "couldn't find input file" error.
