### ISSUE TITLE
Diagonal screen tearing 

### ISSUE THREAD

**Issue by Krisk0s** [calc84maniac/tiboyce#162]
What's wrong, and with what software version?
On TI-OS Version 5.2.2 with TI-Boy CE v0.2.0b installed has an issue with diagonal screen tearing while running games in fullscreen mode. I have no knowledge if this happens on other TI-OS versions

To recreate the tearing run any game in fullscreen. The screen will show diagonal tearing and graphics are offset due to this. This is quite an issue as games such as kirbys dreamland 2 is incredibly hard to see without fullscreen.

**Comment by jacobly0** [comment]
Full screen mode has always had tearing where the top right is one frame ahead of the bottom left, and the fix isn't something that TI-Boy CE can do while still rendering at a reasonable speed.  This is the same tearing that happens while using TIOS, although since TIOS updates more slowly it can be harder to see, I think switching back and forth between the home screen and the graph screen makes it more obvious, Technically, 1x mode also has tearing but the seam was manipulated to run from the top left of the screen past the bottom left corner of the window and happens to be fully off screen.

**Comment by calc84maniac** [comment]
In addition to what jacobly said, this is also the specified behavior in the readme under the fullscreen option. If there was a reasonable way to fix this, I'd do it in a heartbeat, but we'd have to make some major discovery related to the LCD hardware for that to be possible.

**Comment by calc84maniac** [comment]
Reopening this issue because we did actually made some major discoveries regarding the LCD hardware and it appears it should be possible to avoid the tearing in fullscreen. I've been experimenting with various solutions, and once it's stable I think I'd like to try making a minor release so it can get some public testing while I resume development on GBC support.

**Comment by calc84maniac** [comment]
Fixed in v0.2.1 release!
