### ISSUE TITLE
Space Invaders (Japan) wipes RAM

### ISSUE THREAD

**Issue by TrashBandatcoot** [calc84maniac/tiboyce#174]
**TI-OS version:** 5.6.1.0012
**TI-Boy CE version:** Alpha v0.2.1
**Describe your issue:** Space Invaders (Japanese non-SGB version, CRC32 868B57B2) wipes my RAM completely when trying to load the title screen.

What are the steps to reproduce this issue?
-------------------------------------------
1. Open the game and wait for the title screen to show up.
2. There's no step 2, as soon as a part of the logo appears, the calculator flashes to a white screen and wipes RAM.

**Comment by calc84maniac** [comment]
I was able to replicate this crash on the current release. It appears to be some kind of null pointer reference during rendering, but it seems to be fixed in my development build for the next version (since I updated a lot of things related to rendering for GBC support). If I have time, I may look more into exactly what was causing it just to figure out what fixed it.

**Comment by calc84maniac** [comment]
Fixed in v0.3.0.
