### ISSUE TITLE
Possible to convert 8xv back to ROM/Save ?

### ISSUE THREAD

**Issue by afonsosr1v** [calc84maniac/tiboyce#200]
Is it possible at the momment? Could it be possible?

**Comment by calc84maniac** [comment]
You can easily convert saves on this page: https://calc84maniac.github.io/tiboyce/saveconverter/

There's currently no tool for converting ROMs back into a flat file, because I don't think there's all that much use for it. As for save states, they're fundamentally incompatible between different emulators, though I've considered making a converter for the [BESS](https://github.com/LIJI32/SameBoy/blob/master/BESS.md) format which is supported by several major emulators now.

**Comment by afonsosr1v** [comment]
thank you so much
