### ISSUE TITLE
Save converting

### ISSUE THREAD

**Issue by Notyourmom84** [calc84maniac/tiboyce#210]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.7.0
**TI-Boy CE version:** 0.3.0
**Describe your issue:**  
Trouble converting save from calculator to an online emulator
What are the steps to reproduce this issue?
-------------------------------------------
1. I downloaded the file ending in SAV from my calculator
2. then I used the converter on https://calc84maniac.github.io/tiboyce/saveconverter/ to convert to a .sav file
3. when I try using the .sav file on an emulator it doesn't work
4. Next I tried changing the ending of the .sav file to .save since this is the format the online emulator uses when it downloads a save. This again didn't work.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![Screen Shot 2024-04-09 at 9 33 11 AM](https://github.com/calc84maniac/tiboyce/assets/166519154/f8a02050-be26-4d3f-8962-06b8c573c8b2)
![Screen Shot 2024-04-09 at 9 37 32 AM](https://github.com/calc84maniac/tiboyce/assets/166519154/53008820-8a89-4a44-a23f-51ead8311c2c)
![Screen Shot 2024-04-09 at 9 36 39 AM](https://github.com/calc84maniac/tiboyce/assets/166519154/10d883cf-9bc6-4a88-b3f8-00b61cbfde71)
I tried converting both pokemon yellow and pokemon crystal but had no success.
I also noticed that the file sizes prior to converting Pkmn Y and Pkmn were different, but after converting they became the same size (33KB).
Some help with this would be really appreciated. 
The emulator site I'm using is [redacted], I also got the roms from said site (allegedly).

**Comment by calc84maniac** [comment]
The save files being the same size after converting is a good sign. They're compressed on the calculator so that's why they're different sizes before.

That website (which I'll be redacting from the issue by the way) seems to download saves in a custom save state format, with no option for standard cartridge saves. It might be possible to hack a cartridge save into one of those save states, but you're probably better off getting a good emulator on your PC like BGB, Emulicious, or SameBoy. If you're set on using your browser, BinjGB is a good choice over whatever undocumented junk is being used on that site.

**Comment by Notyourmom84** [comment]
Thank you so much for quick response and the help! I used Sameboy to import the save and it worked!
