### ISSUE TITLE
Playing for a long time causes memory errors even if there's more than enough space

### ISSUE THREAD

**Issue by jcgter777** [calc84maniac/tiboyce#43]
I had 1630 something Kb left, and when I exited, it would error, and say I needed to Garbage collect because Archive was full. The first time this happened, I went with it, (garbage collected) and I lost the saves. After that I never garbage collected. Just went with it. The only bad thing was that the saves were stuck in RAM. And I couldn't use save states.

**Comment by calc84maniac** [comment]
I'm going to need more information here.

First of all, what was the "error" you saw, if any? If it was the Garbage Collect itself, that's not an error.

Secondly, what do you mean by "lost the saves"? Did the Garbage Collect fail? Were the files missing?

When you say you never garbage collected after that, does that mean you selected "No" when you were prompted? What happened when you tried to use save states?

**Comment by calc84maniac** [comment]
To some extent, I expect most of that (the screen being funny probably means I'm not clearing out something related to MathPrint, because while I do try to clean up everything I can before Archiving files, it's possible I missed something).

Saves being deleted is something I don't expect, though. That's after the Garbage Collect succeeds?

**Comment by jcgter777** [comment]
Saves do get deleted after Garbage collect succeeds.

**Comment by jcgter777** [comment]
If I do a garbage collect after exiting the mem full error from the homescreen, it succeeds and nothing is deleted. 

Also, it happened after saving to multiple slots. And recalling them quite often.

**Comment by calc84maniac** [comment]
This should hopefully be fixed by https://github.com/calc84maniac/tiboyce/commit/8cd00a085f552d175848fe1ff59388f88a7e3ab6.

Now, if you refuse to Garbage Collect or the file won't fit in Archive even after Garbage Collecting, it will leave the file in RAM and display a warning. Just keep in mind that if too many files get left in RAM, you'll end up getting booted out of the game after saving the state if there's not enough memory to resume. (This will also prevent saving an auto state, but since you just saved a manual state you can load that back after you free up enough RAM.)
