### ISSUE TITLE
game boy color games

### ISSUE THREAD

**Issue by ghost** [calc84maniac/tiboyce#53]
When will you allow Gameboy color games available to play on this

**Comment by LAX18** [comment]
I heard that every time someone asks, the date gets pushed back a week, perhaps more. 

Whenever @calc84maniac gets around to it, it will be done (if ever)

Also, you *can* play some GB Color games already, all black cart games (iirc) can be played.

**Comment by jcgter777** [comment]
BOI

**Comment by LAX18** [comment]
BOI who?

**Comment by jcgter777** [comment]
him

**Comment by LAX18** [comment]
Ah understandable, have a great day

**Comment by jcgter777** [comment]
YEET

**Comment by jcgter777** [comment]
Well, @berniepie11 to answer your question, maybe a few months. There are 16 other issues to get to.

**Comment by calc84maniac** [comment]
Could we please have a modicum of maturity around here? This isn't the playground. The poor guy even deleted his account; though I can't say for sure why, I can guess.

There's no such thing as a dumb question (though if it's a duplicate, I'll mark it as one). It's certainly true that there's currently no tracking on GitHub for GBC support, and I'll probably make a new issue to replace this so people can easily see the status of it.

I can't say for sure that I'll have even _started_ on GBC in a few months time, but it's not like all the current issues will necessarily be addressed first, either. I'll try to get better at tracking my planned tasks in the issue tracker, because most of the things that are _actually_ blocking GBC aren't even listed at this point.
