### ISSUE TITLE
TI-Boy CE v0.1.2 comes up as malware

### ISSUE THREAD

**Issue by mpezent** [calc84maniac/tiboyce#72]
When I try to download v0.1.2 Bit-defender shows it as a malware and so does Firefox.

**Comment by Eeems** [comment]
Can confirm, Firefox shows this as a virus.
@calc84maniac you're going to want to do a scan of your machine.

**Comment by calc84maniac** [comment]
Looks like a false positive on the save converter. No idea why it got flagged so badly, though, or what I can do about it. For now I guess I could add another release zip without the executables, since the online converters are a sufficient alternative.

(By the way, I scanned my machine with Malwarebytes and things look totally clean.)

I would greatly appreciate if you could submit the file as a [false positive](https://www.bitdefender.com/submit/) to Bitdefender, I would do it myself but I don't think I'm eligible to use their support as a non-subscriber.

**Comment by calc84maniac** [comment]
The new release should have fixed this issue, so I'm closing it for now. Still, feel free to submit the false positive if you want to, if only for the sake of improving antivirus engines.

**Comment by Eeems** [comment]
Just a quick followup, VirusTotal shows the zip file as safe: https://www.virustotal.com/gui/url/566a64ed9fd9207a4ea7c1f637a67d82e2828f1767ec247306792e9dce475a77/detection
