### ISSUE TITLE
Some rom hacks and translations work!

### ISSUE THREAD

**Issue by MaverickHunter07** [calc84maniac/tiboyce#79]
All ROM hacks and translation that I've ever tried have worked. I don't know if ROM translations are even dangerous in the first place, because Calc84Maniac only talked about rom hacking. But they're from the same website, so eh.

**Comment by Eeems** [comment]
I'm a little confused by the purpose of this issue?

**Comment by MaverickHunter07** [comment]
Oh, see https://github.com/calc84maniac/tiboyce/issues/47

**Comment by Eeems** [comment]
Again, still not sure what the purpose of having an issue open saying things work is.

**Comment by calc84maniac** [comment]
There is no real difference between ROM hacks (translations are also hacks) and officially released games, except that the ROM hacks may not have been tested on actual Game Boy hardware.

In that regard, when reporting issues with ROM hacks, you should verify the issue against an accurate emulator such as BGB, running in original Game Boy mode (or on actual hardware if you have a flash cart).

At any rate, since this is not actually an issue with TI-Boy, I'm going to close it.

**Comment by MaverickHunter07** [comment]
ok, go ahead

**Comment by calc84maniac** [comment]
Now that I think about it, though, I'd forgotten the old idea I had of making a compatibility wiki. I'll have to look into doing that when I have some spare time.

**Comment by MaverickHunter07** [comment]
I'll look forward to that!
