### ISSUE TITLE
Beatmania GB ram clear after inputing password

### ISSUE THREAD

**Issue by rikoslover** [calc84maniac/tiboyce#86]
I recently got a TI-84+CE and decided to get Ti-boy ce
When playing Beatmania GB (a gbc game) it resets the ram a minute after inputing a game password in the password section. The game worked fine when I didn’t use the password though.

TI-OS: 5.3.0 (I think, It’s the newest version.)
TI-Boy CE OS: ALPHA 
When not using passwords the game runs normally but when i insert a password it resets the ram.

1. Boot game
2. On main screen choose password
3. type UUDDLRLRBA
4. after hitting ok and doing whatever you want itll reset within a minute

**Comment by ndye** [comment]
Hmm.. Probably a lack of proper support. Not all GBC games currently run properly because the full support has not been added yet and they tend to run slow and crash more often than regular GB Games @calc84maniac has a list of performance improvements that he has on the roadmap towards full GBC Support you can follow his progress here: #54

**Comment by calc84maniac** [comment]
Couldn't reproduce this in v0.2.0, feel free to reopen the issue if it still exists in this version.
